before_script:
  - export PATH=$PATH:/usr/bin/

stages:
  - deployBe

deploy:
  stage: deployBe
  tags:
    - cicd
  only:
    - cicd
  script:
   - sudo npm i -g @nestjs/cli
   - npm install
   - echo "MONGO_URI=${MONGO_URI}" >> .env.production 
   - echo "APP_PORT=3000" >> .env.production 
   - npm run build
   - ssh $SSH_USER@$SSH_SERVER_IP "/bin/mkdir -p ${PATH_TO_PROJECT}"
   - rsync -a -e "ssh" . $SSH_USER@$SSH_SERVER_IP:$PATH_TO_PROJECT --delete
   - ssh $SSH_USER@$SSH_SERVER_IP
   - pm2 stop all
   - cd ${PATH_TO_PROJECT}
   - pm2 start dist/main.js
   - exit
