before_script:
  - export PATH=$PATH:/usr/bin/

stages:
  - deployBe

deploy:
  stage: deployBe
  tags:
    - cicd
  only:
    - master
  script:
   - npm install
   - echo "MONGO_URI=${MONGO_URI}" >> .env.production 
   - echo "APP_PORT=3000" >> .env.production 
   - npm run gen
   - npm run build
   - ssh $SSH_USER@$SSH_SERVER_IP "/bin/mkdir -p ${PATH_TO_PROJECT}; pm2 kill"
   - rsync -a -e "ssh" . $SSH_USER@$SSH_SERVER_IP:$PATH_TO_PROJECT --delete
   - ssh $SSH_USER@$SSH_SERVER_IP "cd ${PATH_TO_PROJECT}; NODE_ENV=production pm2 start dist/main.js"

